name: hackground_app
description: Hackround App TraVeland.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  latlong2: ^0.8.1
  sliding_up_panel: ^2.0.0+1

  cupertino_icons: ^1.0.2
  flutter_map: ^3.0.0
  google_polyline_algorithm: ^3.1.0
  flutter_map_marker_popup: ^4.0.0
  location: ^4.2.0
  geocoding: ^2.0.5
  dio: ^4.0.6
  auto_route: ^5.0.3
  webview_flutter: ^3.0.4
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  retrofit: '>=3.0.0 <4.0.0'
  logger: any  #for logging purpose
  json_annotation: ^4.7.0
  provider: ^6.0.3
  reflectable: ^4.0.0
  flutter_svg: ^1.1.6
  dropdown_button2: ^1.9.2
  flutter_secure_storage: ^7.0.1
  email_validator: '^2.1.16'
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.7
  loadmore: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3           
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: ^2.1.11
  json_serializable: '^6.3.1'


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - lang/ru.json
    - lang/en.json
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  #   - lib/assets/images/tabs_screen_svg/shedule.svg
  #   - lib/assets/images/photo_2022-05-14_12-40-59.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets\fonts\rubik\Rubik-Regular.ttf
        - asset: assets\fonts\rubik\Rubik-Medium.ttf
          weight: 700
        - asset: assets\fonts\rubik\Rubik-Bold.ttf
          weight: 900
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
