name: hackground_app
description: Hackround App TraVeland.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  latlong2: ^0.8.1
  sliding_up_panel: ^2.0.0+1

  cupertino_icons: ^1.0.2
  flutter_map: ^3.0.0
  google_polyline_algorithm: ^3.1.0
  flutter_map_marker_popup: ^4.0.0
  location: ^4.2.0
  geocoding: ^2.0.5
  dio: ^4.0.6
  auto_route: ^5.0.3
  webview_flutter: ^3.0.4
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3           
  build_runner: 


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - lang/ru.json
    - lang/en.json

  # To add assets to your application, add an assets section, like this:
  #   - lib/assets/images/tabs_screen_svg/shedule.svg
  #   - lib/assets/images/photo_2022-05-14_12-40-59.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # # example:
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: hackground_app\lib\assets\Roboto\Roboto-Black.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
